---
subsetName: default subset
description: Default set of comparisons
configuration:
    - ref: default
      test: default
    - ref: bcstc
      test: bcstc
    - ref: newProcessors
      test: newProcessors
