---
description:
    These parameters are used by the Jenkins job
    validating the new development in the validation code
parameters:
    cmsswRemote: ebecheva
    cmsswBranch: testJenkins-fix-CMSSW_12_5_2_patch1
